### ISSUE TITLE
Crash in Steam Offline mode

### ISSUE THREAD

**Issue by gxm11** [GMMan/RGSS_SteamUserStatsLite#2]
My rmxp game crashed in offline mode, that means: steam is open, but cannot connect to the Internet.
It seems cost very long time for response after executing `@@dll_SteamAPI_Init.call`, which finally leads to crash.
```ruby
class SteamUserStatsLite
  # Instantiates a new instance of +SteamUserStatsLite+.
  def initialize
    @initted = false
    api_initted = @@dll_SteamAPI_Init.call % 256 != 0
    if api_initted
      @context = SteamAPIContext.new
      if @context.initted?
        @i_apps = @context.steam_apps
        @i_user_stats = @context.steam_user_stats
        @initted = true
      end
    end
  end
...
```
I change this method like code below, and problem solved.
```ruby
def initialize
  @initted = false
  @context = SteamAPIContext.new
  if @context.initted? && @@dll_SteamAPI_Init.call % 256 != 0
    @i_apps = @context.steam_apps
    @i_user_stats = @context.steam_user_stats
    @initted = true
  end
end
```
By the way, I don't know why there's some one prefer running steam games in offline mode. :]

**Comment by GMMan** [comment]
Could you link to a sample project? I can't seem to reproduce it, at least not on VX Ace.

**Comment by GMMan** [comment]
Closing as not reproducible.
